# Generated by Django 3.2.7 on 2021-10-28 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(verbose_name='Текст')),
                ('photo', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('published', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.university')),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
    ]
