# Generated by Django 3.2.7 on 2021-10-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('nickname', models.CharField(max_length=255, null=True, verbose_name='Никнейм пользователя')),
                ('first_name', models.CharField(max_length=255, null=True, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(max_length=255, null=True, verbose_name='Фамилия пользователя')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('photo', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d', verbose_name='Фото пользователя')),
                ('send_mail', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'имя пользователя',
                'verbose_name_plural': 'Имена пользователей',
            },
        ),
    ]
